import { BookOpen, Coffee, Sparkles, Eye } from 'lucide-react';

export const VIBES = {
  study: {
    id: 'study',
    label: 'Study Mode',
    description: 'Focused, structured, productive',
    icon: BookOpen,
    config: {
      defaultSpeed: 28,
      pageMargin: 14,
      autoHideDelay: 3500,
      controlSize: 'md',
      scrollSmoothness: 0.88,
      uiDensity: 'compact',
      accentColor: '#6E8BFF',
      ambientPreset: null,
      pageAlignment: 'left',
      animationIntensity: 'subtle',
      densityClass: 'tracking-normal',
      bgOverlay: 'rgba(11, 12, 15, 0.0)',
      pageRadius: '4px',
      pageShadow: '0 4px 16px rgba(0,0,0,0.5)',
      progressHeight: '3px',
      fontScale: 1,
      controlsAlwaysVisible: true,
    },
  },
  casual: {
    id: 'casual',
    label: 'Casual Reading',
    description: 'Calm, cozy, immersive flow',
    icon: Coffee,
    config: {
      defaultSpeed: 38,
      pageMargin: 28,
      autoHideDelay: 2200,
      controlSize: 'md',
      scrollSmoothness: 0.93,
      uiDensity: 'normal',
      accentColor: '#6E8BFF',
      ambientPreset: null,
      pageAlignment: 'center',
      animationIntensity: 'medium',
      densityClass: 'tracking-normal',
      bgOverlay: 'rgba(11, 12, 15, 0.0)',
      pageRadius: '8px',
      pageShadow: '0 8px 40px rgba(0,0,0,0.45)',
      progressHeight: '3px',
      fontScale: 1,
      controlsAlwaysVisible: false,
    },
  },
  manga: {
    id: 'manga',
    label: 'Manga / Comic',
    description: 'Cinematic visual immersion',
    icon: Sparkles,
    config: {
      defaultSpeed: 22,
      pageMargin: 48,
      autoHideDelay: 1800,
      controlSize: 'sm',
      scrollSmoothness: 0.96,
      uiDensity: 'sparse',
      accentColor: '#FF6B9E',
      ambientPreset: null,
      pageAlignment: 'center',
      animationIntensity: 'strong',
      densityClass: 'tracking-tight',
      bgOverlay: 'rgba(0, 0, 0, 0.3)',
      pageRadius: '2px',
      pageShadow: '0 16px 60px rgba(0,0,0,0.7)',
      progressHeight: '2px',
      fontScale: 1,
      controlsAlwaysVisible: false,
    },
  },
  accessibility: {
    id: 'accessibility',
    label: 'Accessibility',
    description: 'Larger, gentler, high contrast',
    icon: Eye,
    config: {
      defaultSpeed: 16,
      pageMargin: 32,
      autoHideDelay: 6000,
      controlSize: 'lg',
      scrollSmoothness: 0.85,
      uiDensity: 'comfortable',
      accentColor: '#5DD39E',
      ambientPreset: null,
      pageAlignment: 'center',
      animationIntensity: 'none',
      densityClass: 'tracking-wide',
      bgOverlay: 'rgba(11, 12, 15, 0.0)',
      pageRadius: '6px',
      pageShadow: '0 4px 20px rgba(0,0,0,0.5)',
      progressHeight: '5px',
      fontScale: 1.1,
      controlsAlwaysVisible: true,
    },
  },
};

export const DEFAULT_VIBE = 'casual';